name: Check Migration
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - 'main'

jobs:
  check_migration:
    runs-on: ubuntu-22.04
    name: Test changed-files
    steps:
      # Fetch the latest code (for this branch)
      - uses: actions/checkout@v3

      # Check if any migrations exist
      # (could also just check for the label if it runs after labeler.yml)
      - name: Find any new migrations
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/migrations/*.py

      # If no migrations, the job ends here!

      # Install python package github_commit_status
      - name: setup python
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install github_commit_status

      # Check status of _this_ branch
      - name: execute script
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          CURRENT=$(git rev-parse --abbrev-ref HEAD)
          chmod +x update-status.sh
          mkdir -p test/
          cd test/ && ../update-status.sh $CURRENT
        shell: bash
        env:
          GITHUB_COMMIT_STATUS_TOKEN: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}
