name: Check Migration
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  workflow_run:
    workflows: [Run on main]
    types:
      - completed
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - 'main'

jobs:
  check_migration:
    runs-on: ubuntu-22.04
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Find any new migrations
      #   id: changed-files-specific
      #   uses: tj-actions/changed-files@v35
      #   with:
      #     files: |
      #       **/migrations/*.py

      # - name: Check if branch is behind dev
      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
      #   run: |
      #     CURRENT=$(git rev-parse --abbrev-ref HEAD)
      #     TEST=$(git rev-list --left-right --count origin/main...origin/$CURRENT)
      #     stringarray=($TEST)
      #     BEHIND=${stringarray[0]}
      #     if [[ $BEHIND != 0 ]]; then
      #       exit 1;
      #     fi

      - name: execute script
        run: |
          CURRENT=$(git rev-parse --abbrev-ref HEAD)
          chmod +x update-status.sh
          mkdir -p test/
          cd test/ && ../update-status.sh $CURRENT
        shell: bash
        env:
          GITHUB_COMMIT_STATUS_TOKEN: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}
