name: Run on main
on:
  push:
    branches:
      - main

jobs:
  run-on-main:
    runs-on: ubuntu-22.04
    name: Trigger
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # - name: Trigger other PRs
      #   run: |
      #     chmod +x run-checker.sh
      #     ./run-checker.sh
      #   shell: bash
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install github_commit_status

      - name: execute py script
        run: |
          mkdir -P test/ && cd test/ && ./update-status.sh
        shell: bash
        env:
          GITHUB_COMMIT_STATUS_TOKEN: ${{ secrets.gh_token }}

