name: Run on main
on:
  push:
    branches:
      - main

# THIS JOB RUNS EVERY TIME SOMETHING IS PUSHED
# TO THE DEFAULT BRANCH

jobs:
  run-on-main:
    runs-on: ubuntu-22.04
    name: Trigger
    steps:
      # Fetch the latest code (to have the scripts)
      - uses: actions/checkout@v3

      # Install python package github_commit_status
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install github_commit_status

      # Check all (relevant) branches
      - name: execute script
        run: |
          chmod +x update-status.sh
          mkdir -p test/
          cd test/ && ../check-all.sh
        shell: bash
        env:
          GITHUB_COMMIT_STATUS_TOKEN: ${{ secrets.gh_token }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}

