name: Run on main
on:
  push:
    branches:
      - main

jobs:
  run-on-main:
    runs-on: ubuntu-22.04
    name: Trigger
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Trigger other PRs
        run: |
          chmod +x run-checker.sh
          ./run-checker.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
