name: Run on main
on:
  push:
    branches:
      - main

jobs:
  run-on-main:
    runs-on: ubuntu-22.04
    name: Trigger
    steps:
      - name: Trigger other PRs
        run: ./run-checker.sh
        shell: bash
